import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const radius = width * 0.4;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 20,
  },
  chartContainer: {
    width: radius * 2,
    height: radius * 2,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  note: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    bottom: 80,
  },
  noteText: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  circle: {
    position: 'absolute',
    width: radius * 2,
    height: radius * 2,
    borderRadius: radius,
    borderColor: 'rgba(255,255,255,0.3)',
    borderWidth: 2,
    bottom: -50,
  },
  keyInfoContainer: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 10,
    alignItems: 'center',
  },
  keyInfoText: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
  },
  scaleContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  scaleTitle: {
    display: 'none',
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    bottom: -55,
  },
  scaleNotesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    position: 'absolute',
    bottom: -95,
  },
  scaleNote: {
    color: '#fff',
    fontSize: 16,
    marginHorizontal: 5,
    marginVertical: 2,
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
  },
  bpmContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 25,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginTop: 20,
    position: 'absolute',
    bottom: 40,
  },
  bpmLabel: {
    color: '#fff',
    fontSize: 18,
    marginRight: 10,
  },
  bpmValue: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  scaleTypeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 200,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 10,
  },
  scaleTypeButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginHorizontal: 10,
  },
  selectedScaleTypeButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  scaleTypeButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  confirmKeyButton: {
    position: 'absolute',
    top: 120,
    left: 20,
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  confirmedKeyButton: {
    backgroundColor: '#333',
  },
  confirmButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  confirmedButtonText: {
    color: '#000',
  },
  roleKeyButton: {
    position: 'absolute',
    top: 120,
    right: 20,
    backgroundColor: '#f44336',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  roleKeyButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  dragIndicator: {
    position: 'absolute',
    bottom: 450,
    backgroundColor: 'rgba(255,255,255,0.2)',
    padding: 10,
    borderRadius: 10,
  },
  dragIndicatorText: {
    color: '#fff',
    fontSize: 16,
  },
});

export default styles;
